services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  database:
    image: postgres:16-alpine
    container_name: database
    environment:
      POSTGRES_DB: k_db_dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
        - "5432:5432"
    volumes:
      - k_dev-data:/var/lib/postgresql/data


volumes:
    k_dev-data: