server:
  port: ${PORT:8080}
spring:
  data:
    redis:
      host: ${REDIS_HOST}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
logging:
  level:
    root: INFO
    org.springframework.security: WARN
    org.springframework.security.oauth2: WARN
    org.springframework.web.client: WARN
